from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from donebench.core.validation import validate_tasks


@dataclass(frozen=True)
class Artifact:
    path: str
    description: str
    required: bool = True


ARTIFACTS = [
    Artifact("README.md", "Top-level setup, one-command reproduction, Docker, and API notes."),
    Artifact("Dockerfile", "Pinned Python 3.12 container used for local smoke reproduction."),
    Artifact(".devcontainer/devcontainer.json", "VS Code/Codespaces-compatible development container."),
    Artifact("Makefile", "Reviewer entry points: repro-smoke, repro-package, docker-smoke, cost-report."),
    Artifact("pyproject.toml", "Package metadata and Python dependencies."),
    Artifact("configs/experiments.yaml", "Named experiment suites, splits, agents, and retry-friendly worker recommendations."),
    Artifact("configs/models.yaml", "Provider/model identifiers, credential environment variables, and decoding settings."),
    Artifact("data/tasks/", "Benchmark tasks with gold DoneSpec criteria and near-miss states."),
    Artifact("donebench/", "Benchmark, DSL, agents, experiment runner, and reporting scripts."),
    Artifact("tests/", "Unit and smoke tests for schemas, metrics, artifact utilities, and CLI paths."),
    Artifact("results/smoke.jsonl", "Local deterministic smoke traces generated by make smoke.", required=False),
    Artifact("results/smoke.manifest.json", "Smoke run manifest with skipped-model accounting.", required=False),
    Artifact("results/topconf_deepseek_core_trial0.jsonl", "API-backed trial traces used by cost and failure reports.", required=False),
    Artifact("reports/repro_manifest.json", "Machine-readable reproducibility manifest.", required=False),
    Artifact("reports/costs/", "Token, cost, latency, and attempt summaries from API traces.", required=False),
    Artifact("reports/quality/", "Task quality audit outputs.", required=False),
    Artifact("reports/quality/task_construction_datasheet.md", "Dataset construction datasheet and leakage/templating caveats.", required=False),
    Artifact("reports/stats/", "Advanced statistics and confidence interval tables.", required=False),
    Artifact("reports/failures/", "Failure mining tables for qualitative analysis.", required=False),
    Artifact("paper/main.tex", "Paper draft scaffold.", required=False),
    Artifact("paper/tables/", "Paper table CSV snapshots/templates.", required=False),
    Artifact("paper/figures/", "Generated figure PNGs.", required=False),
]


CHECKLIST = [
    ("Environment", "Dockerfile and .devcontainer are included; local path is python -m pip install -e \".[dev]\"."),
    ("One-command smoke", "make repro-smoke validates tasks, runs the mock smoke suite, regenerates figures, and refreshes manifests."),
    ("Offline path", "Smoke reproduction uses mock/heuristic paths and does not require external model APIs."),
    ("Live model access", "configs/models.yaml lists provider model ids, credential env vars, base URLs, and notes."),
    ("Costs and latency", "donebench cost-report writes per-call and by-model token/cost/latency summaries under reports/costs/."),
    ("Retry/resume", "run-matrix supports --resume and --max-workers; provider adapters record attempts in diagnostics."),
    ("Skipped credentials", "Missing credentials are recorded in *.manifest.json when skip_missing_credentials is true."),
    ("Artifacts", "reports/openreview_package_manifest.md records required and optional files for the package."),
    ("Paper build", "make paper compiles paper/main.tex when a TeX distribution is installed."),
]


def export_package(root: Path = Path(".")) -> Path:
    reports = root / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    out = reports / "openreview_package_manifest.md"
    task_count = _task_count(root / "data" / "tasks")
    lines = [
        "# OpenReview Package Manifest",
        "",
        f"Generated task count: {task_count}",
        "",
        "## Required Files",
        "",
    ]
    lines.extend(_artifact_lines(root, required=True))
    lines.extend(["", "## Optional Generated Artifacts", ""])
    lines.extend(_artifact_lines(root, required=False))
    lines.extend(
        [
            "",
            "## Reviewer Entry Points",
            "",
            "- Local setup: `python -m pip install -e \".[dev]\"`",
            "- One-command local smoke reproduction: `make repro-smoke`",
            "- Container smoke reproduction: `make docker-smoke`",
            "- Refresh package metadata without rerunning experiments: `make repro-package`",
            "- API token/cost/latency summary: `make cost-report COST_INPUT=results/<run>.jsonl`",
        ]
    )
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _write_checklist(reports / "openreview_checklist.md")
    _write_model_notes(reports / "model_access_cost_latency_retry.md")
    return out


def _task_count(task_root: Path) -> int:
    try:
        tasks, errors = validate_tasks(task_root)
    except Exception:
        return 0
    if errors:
        return 0
    return len(tasks)


def _artifact_lines(root: Path, required: bool) -> list[str]:
    lines = []
    for artifact in ARTIFACTS:
        if artifact.required != required:
            continue
        path = root / artifact.path
        status = "present" if path.exists() else ("missing" if required else "not generated")
        detail = _artifact_detail(path)
        suffix = f" ({detail})" if detail else ""
        lines.append(f"- [{status}] `{artifact.path}`{suffix}: {artifact.description}")
    return lines


def _artifact_detail(path: Path) -> str:
    if not path.exists():
        return ""
    if path.is_file():
        return f"{path.stat().st_size} bytes"
    file_count = sum(1 for child in path.rglob("*") if child.is_file())
    return f"{file_count} files"


def _write_checklist(path: Path) -> None:
    lines = ["# OpenReview Reproducibility Checklist", ""]
    for title, detail in CHECKLIST:
        lines.append(f"- [x] {title}: {detail}")
    lines.extend(
        [
            "",
            "Reviewer notes:",
            "",
            "- External API runs are intentionally separated from offline smoke reproduction.",
            "- API-backed results should be reported with provider access dates, enabled model ids, and missing-credential skips.",
            "- The package records retry attempts per parsed LLM call in result diagnostics and summarizes them in reports/costs/api_call_costs.csv.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_model_notes(path: Path) -> None:
    lines = [
        "# Model Access, Cost, Latency, and Retry Notes",
        "",
        "## Access",
        "",
        "- Live model credentials are read only from environment variables listed in `configs/models.yaml`.",
        "- Supported external keys include `OPENAI_API_KEY`, `DEEPSEEK_API_KEY`, `ANTHROPIC_API_KEY`, `GEMINI_API_KEY`, and `OPENROUTER_API_KEY`.",
        "- Local endpoints use `OLLAMA_BASE_URL` or `VLLM_BASE_URL` and are disabled by default until explicitly enabled in `configs/models.yaml`.",
        "- Missing credentials are skipped when `skip_missing_credentials: true`; skips are written to the run `.manifest.json`.",
        "",
        "## Cost and Latency",
        "",
        "- Run `donebench cost-report results/<run>.jsonl reports/costs` to produce per-call and by-model CSVs.",
        "- `reports/costs/api_call_costs.csv` includes input tokens, output tokens, latency seconds, attempts, estimation flags, and estimated cost.",
        "- `reports/costs/api_cost_by_model.csv` aggregates calls, tokens, total latency, mean latency, and estimated USD cost.",
        "- Prices are estimates for configured DeepSeek models in `donebench/scripts/cost_report.py`; update that table for other providers before claiming dollar totals.",
        "",
        "## Retry and Resume",
        "",
        "- Provider calls default to three attempts with linear backoff controlled by model `extra.attempts` and `extra.retry_backoff_s`.",
        "- Parsed LLM diagnostics include `attempts`, `latency_s`, `usage`, `provider`, and `provider_model` when the provider returns metadata.",
        "- Long API suites should use `--resume`; completed `(task_id, agent, model, trial)` rows are not recomputed.",
        "- If rate limits occur, rerun the same command with lower `--max-workers` values while keeping `--resume`.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
